version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
  - package-ecosystem: bundler
    directory: '/ruby'
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: '/typescript'
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
