version: 2
updates:
- package-ecosystem: bundler
  directory: "/ruby"
  schedule:
    interval: daily
    time: '11:00'
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/typescript"
  schedule:
    interval: daily
    time: '11:00'
  open-pull-requests-limit: 10
